baseURL = "https://qqhann.info"
languageCode = "ja"
title = "qqhann"
theme = "hugo-primer"
hasCJKLanguage = true
summaryLength = 70
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-87782758-5"
disqusShortname="qqhann"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
description = "Qiushi(a.k.a. qqhann)'s web site. Find my information, my blog on technologies and personal hobbies here."
twitter = "qqhann"
useIcon = true
useTwitterCard = true
shareTo = ["Twitter", "Hatena", "Facebook"]
creditHugoPrimer = true
