baseURL = "https://www.gitshell.net"
languageCode = "en-us"
title = "ghoostqq"
theme = "theer"
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-87782758-2"

[[menu.main]]
  name = "Info"
  weight = 1
  url = "/"

[[menu.main]]
  name = "Blog"
  weight = 2
  url = "/blog"
